<?php

if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
}

function getDataURI($image, $mime = '') {
    return 'data: '.(function_exists('mime_content_type') ? mime_content_type($image) : $mime).';base64,'.base64_encode(file_get_contents($image));
}

$uploadedfile = $_FILES['file'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && ! isset( $movefile['error'] ) ) {
    
    $img = wp_get_image_editor( $movefile['file'] );
    
    if ( ! is_wp_error( $img ) ) {
        $img->resize( 300, 300, true );
        $image = $img->save();
        
        $url = site_url('/' . stristr($image['path'], 'wp-content'));
        $id = get_current_user_id();
        
        global $wpdb;
        
        $prefix = $wpdb->prefix;
        
        if ( $wpdb->get_var('SELECT userid FROM ' . $prefix.'user_extends' . ' WHERE userid = ' . $id ) == $id ){
            $wpdb->update( $prefix.'user_extends', [ 'picture' => $url ], 'userid = ' . $id );
        } else {
        
            $wpdb->insert( $prefix.'user_extends', [
                'userid' => $id,
                'picture' => getDataURI($url),
            ]);
        }
        
        
        $data = unserialize(file_get_contents(__DIR__ . '/data.txt'));
        $data[$id] = $url;   
        file_put_contents(__DIR__ . '/data.txt', serialize($data));
    }
    ?>

<div class="warp">
    <h2>Your picture profile</h2>
    <img src="<?php echo $url; ?>" />
</div>

    <?php
    
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}

